# Generated by Django 4.2.6 on 2024-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
